/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Modelos.Auto;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Daniel
 */
public class AutoGui extends javax.swing.JPanel {
    
    /**
     * Creates new form AutoGui
     */
    public AutoGui() {
        initComponents();
    }
    
    public AutoGui(Auto auto) {
        initComponents();
        this.idAutoTxt.setText(auto.getId() + "");
        this.nombreAutoTxt.setText(auto.getNombre());
        this.costeAutoTxt.setText(auto.getCoste() + "");
    }

    public JLabel getCosteAutoLbl() {
        return costeAutoLbl;
    }

    public void setCosteAutoLbl(JLabel costeAutoLbl) {
        this.costeAutoLbl = costeAutoLbl;
    }

    public JTextField getCosteAutoTxt() {
        return costeAutoTxt;
    }

    public void setCosteAutoTxt(JTextField costeAutoTxt) {
        this.costeAutoTxt = costeAutoTxt;
    }

    public JLabel getIdAutoLbl() {
        return idAutoLbl;
    }

    public void setIdAutoLbl(JLabel idAutoLbl) {
        this.idAutoLbl = idAutoLbl;
    }

    public JTextField getIdAutoTxt() {
        return idAutoTxt;
    }

    public void setIdAutoTxt(JTextField idAutoTxt) {
        this.idAutoTxt = idAutoTxt;
    }

    public JLabel getNombreAutoLbl() {
        return nombreAutoLbl;
    }

    public void setNombreAutoLbl(JLabel nombreAutoLbl) {
        this.nombreAutoLbl = nombreAutoLbl;
    }

    public JTextField getNombreAutoTxt() {
        return nombreAutoTxt;
    }

    public void setNombreAutoTxt(JTextField nombreAutoTxt) {
        this.nombreAutoTxt = nombreAutoTxt;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idAutoLbl = new javax.swing.JLabel();
        idAutoTxt = new javax.swing.JTextField();
        nombreAutoLbl = new javax.swing.JLabel();
        nombreAutoTxt = new javax.swing.JTextField();
        costeAutoLbl = new javax.swing.JLabel();
        costeAutoTxt = new javax.swing.JTextField();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        setLayout(new java.awt.GridLayout(3, 2));

        idAutoLbl.setText("ID Auto:");
        add(idAutoLbl);

        idAutoTxt.setEditable(false);
        idAutoTxt.setFocusable(false);
        add(idAutoTxt);

        nombreAutoLbl.setText("Nombre Auto: ");
        add(nombreAutoLbl);

        nombreAutoTxt.setEditable(false);
        nombreAutoTxt.setFocusable(false);
        add(nombreAutoTxt);

        costeAutoLbl.setText("Coste Auto");
        add(costeAutoLbl);

        costeAutoTxt.setEditable(false);
        costeAutoTxt.setFocusable(false);
        add(costeAutoTxt);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel costeAutoLbl;
    private javax.swing.JTextField costeAutoTxt;
    private javax.swing.JLabel idAutoLbl;
    private javax.swing.JTextField idAutoTxt;
    private javax.swing.JLabel nombreAutoLbl;
    private javax.swing.JTextField nombreAutoTxt;
    // End of variables declaration//GEN-END:variables
}
