/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Estructuras.Pila;

/**
 *
 * @author Daniel
 */
public class BasureroGui extends javax.swing.JPanel {

    private Pila pila;
    
    /**
     * Creates new form BasureroGui
     */
    public BasureroGui() {
        initComponents();
        this.pila = new Pila();
        this.setVisible(true);
    }
    
    public BasureroGui(Pila pila) {
        initComponents();
        this.pila = pila;
        this.setVisible(true);
    }

    public Pila getPila() {
        return pila;
    }

    public void setPila(Pila pila) {
        this.pila = pila;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        setLayout(new java.awt.GridLayout(0, 1, 10, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
