/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Modelos.Fabrica;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Daniel
 */
public class FabricaGui extends JFrame {

    private Fabrica fabrica;

    /**
     * Creates new form FabricaGui
     */
    public FabricaGui() {
        initComponents();
        this.setTitle("Ejemplo Fabrica");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.pack();
        this.setVisible(true);
    }

    public FabricaGui(Fabrica fabrica) {
        initComponents();
        this.fabrica = fabrica;
        this.setTitle(fabrica.getNombre());
        this.setLocationRelativeTo(null);
        this.pack();
        this.setVisible(true);
    }

    public JButton getBtnAgregarMaterial() {
        return btnAgregarMaterial;
    }

    public void setBtnAgregarMaterial(JButton btnAgregarMaterial) {
        this.btnAgregarMaterial = btnAgregarMaterial;
    }

    public JButton getBtnDescartarMaterial() {
        return btnDescartarMaterial;
    }

    public void setBtnDescartarMaterial(JButton btnDescartarMaterial) {
        this.btnDescartarMaterial = btnDescartarMaterial;
    }

    public Fabrica getFabrica() {
        return fabrica;
    }

    public void setFabrica(Fabrica fabrica) {
        this.fabrica = fabrica;
    }

    public JPanel getPanelBasurero() {
        return panelBasurero;
    }

    public void setPanelBasurero(JPanel panelBasurero) {
        this.panelBasurero = panelBasurero;
    }

    public JPanel getPanelCinta() {
        return panelCinta;
    }

    public void setPanelCinta(JPanel panelCinta) {
        this.panelCinta = panelCinta;
    }

    public JPanel getPanelConstruccion() {
        return panelConstruccion;
    }

    public void setPanelConstruccion(JPanel panelConstruccion) {
        this.panelConstruccion = panelConstruccion;
    }

    public JPanel getPanelFunciones() {
        return panelFunciones;
    }

    public void setPanelFunciones(JPanel panelFunciones) {
        this.panelFunciones = panelFunciones;
    }

    public JPanel getPanelHub() {
        return panelHub;
    }

    public void setPanelHub(JPanel panelHub) {
        this.panelHub = panelHub;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFunciones = new javax.swing.JPanel();
        btnDescartarMaterial = new javax.swing.JButton();
        btnAgregarMaterial = new javax.swing.JButton();
        panelBasurero = new javax.swing.JPanel();
        panelHub = new javax.swing.JPanel();
        panelCinta = new javax.swing.JPanel();
        panelConstruccion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(30, 30));

        btnDescartarMaterial.setText("Descartar Material");
        panelFunciones.add(btnDescartarMaterial);

        btnAgregarMaterial.setText("Agregar Material");
        panelFunciones.add(btnAgregarMaterial);

        getContentPane().add(panelFunciones, java.awt.BorderLayout.PAGE_START);

        panelBasurero.setBackground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout panelBasureroLayout = new javax.swing.GroupLayout(panelBasurero);
        panelBasurero.setLayout(panelBasureroLayout);
        panelBasureroLayout.setHorizontalGroup(
            panelBasureroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelBasureroLayout.setVerticalGroup(
            panelBasureroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        getContentPane().add(panelBasurero, java.awt.BorderLayout.LINE_START);

        panelHub.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout panelHubLayout = new javax.swing.GroupLayout(panelHub);
        panelHub.setLayout(panelHubLayout);
        panelHubLayout.setHorizontalGroup(
            panelHubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelHubLayout.setVerticalGroup(
            panelHubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        getContentPane().add(panelHub, java.awt.BorderLayout.LINE_END);

        panelCinta.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout panelCintaLayout = new javax.swing.GroupLayout(panelCinta);
        panelCinta.setLayout(panelCintaLayout);
        panelCintaLayout.setHorizontalGroup(
            panelCintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelCintaLayout.setVerticalGroup(
            panelCintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(panelCinta, java.awt.BorderLayout.PAGE_END);

        panelConstruccion.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout panelConstruccionLayout = new javax.swing.GroupLayout(panelConstruccion);
        panelConstruccion.setLayout(panelConstruccionLayout);
        panelConstruccionLayout.setHorizontalGroup(
            panelConstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        panelConstruccionLayout.setVerticalGroup(
            panelConstruccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        getContentPane().add(panelConstruccion, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FabricaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FabricaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FabricaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FabricaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FabricaGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMaterial;
    private javax.swing.JButton btnDescartarMaterial;
    private javax.swing.JPanel panelBasurero;
    private javax.swing.JPanel panelCinta;
    private javax.swing.JPanel panelConstruccion;
    private javax.swing.JPanel panelFunciones;
    private javax.swing.JPanel panelHub;
    // End of variables declaration//GEN-END:variables
}
